language: python

python:
  - '3.7'

before_install:
  - pip install -r tests/requirements.txt

install:
  - pip install -r requirements.txt

script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - benjamin@bengfort.com

    on_success: change
    on_failure: always
